development:
  sessions:
    default:
      database: parkitapp_development
      hosts:
        - localhost:27017
      options:

test:
  sessions:
    default:
      database: parkitapp_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  clients:
    default:
      uri: <%= ENV['MONGOLAB_URI'] %>
      options:
        max_retries: 30 
        retry_interval: 1
        timeout: 15
        refresh_interval: 10
  options:
    raise_not_found_error: false	