development:
  clients:
    default:
      database: parkitapp_development
      hosts:
        - localhost:27017
      options:

test:
  clients:
    default:
      database: parkitapp_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
