development:
  sessions:
    default:
      database: parkitapp_development
      hosts:
        - localhost:27017
      options:

test:
  sessions:
    default:
      database: parkitapp_test
      hosts:
        - localhost:27017
      options:
        read: primary
        max_retries: 1
        retry_interval: 0

production:
  sessions:
    default:
      uri: <%= ENV['MONGOHQ_URL'] %>
      options: